/* tslint:disable */
/* eslint-disable */
/**
 * Todo API
 * Todo API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetUserDto
 */
export interface GetUserDto {
    /**
     * 
     * @type {number}
     * @memberof GetUserDto
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof GetUserDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof GetUserDto
     */
    'email': string;
}

